#!/usr/bin/env python3
"""Generate sqllogictest from certified hash values.

Reads hash_values_v*.json files and produces test/sql/duckdb_bloom_filter.test
with baked-in expected values certified against real DuckDB releases.

Usage:
    python generate_test.py > ../sql/duckdb_bloom_filter.test
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def load_values(version: str) -> dict:
    path = Path(__file__).parent / f"hash_values_{version}.json"
    with open(path) as f:
        return json.load(f)


def emit(line: str = "") -> None:
    print(line)


def main() -> None:
    v151 = load_values("v1.5.1")
    v144 = load_values("v1.4.4")
    v160 = load_values("v1.6.0")

    s = v151["single"]
    m = v151["multi"]
    c = v151["cartesian"]

    emit("# name: test/sql/duckdb_bloom_filter.test")
    emit("# description: Tests for bitfilters_duckdb_hash, bitfilters_duckdb_bloom_filter_create,")
    emit("#              and bitfilters_duckdb_bloom_filter_probe functions.")
    emit("#              Hash values certified against DuckDB v1.4.4, v1.5.1, and v1.6.0 Python packages.")
    emit("#              Generated by test/generate/generate_test.py — do not edit by hand.")
    emit("# group: [bitfilters]")
    emit()
    emit("require bitfilters")
    emit()

    # === Single-value hash tests ===
    emit("# ============================================================================")
    emit("# bitfilters_duckdb_hash — single value, type coverage")
    emit(f"# Values certified against DuckDB v1.5.1 (duckdb=={v151['duckdb_version']})")
    emit("# ============================================================================")
    emit()

    single_tests = [
        ("42::INTEGER", "42_integer"),
        ("42::BIGINT", "42_bigint"),
        ("42::TINYINT", "42_tinyint"),
        ("42::SMALLINT", "42_smallint"),
        ("42::UTINYINT", "42_utinyint"),
        ("42::USMALLINT", "42_usmallint"),
        ("42::UINTEGER", "42_uinteger"),
        ("42::UBIGINT", "42_ubigint"),
        ("42::FLOAT", "42_float"),
        ("42::DOUBLE", "42_double"),
        ("0.0::FLOAT", "0.0_float"),
        ("0.0::DOUBLE", "0.0_double"),
        ("'hello'::VARCHAR", "hello_varchar"),
        ("''::VARCHAR", "empty_varchar"),
        ("'a longer string for testing'::VARCHAR", "long_varchar"),
        ("'\\xDEAD'::BLOB", "dead_blob"),
    ]
    for expr, key in single_tests:
        emit(f"# hash({expr})")
        emit("query I")
        emit(f"SELECT bitfilters_duckdb_hash('v1.5.1', {expr})::UBIGINT;")
        emit("----")
        emit(str(s[key]))
        emit()

    # === Negative integers ===
    emit("# Negative integers (critical: tests sign extension)")
    neg_tests = [
        ("(-1)::TINYINT", "neg1_tinyint"),
        ("(-1)::SMALLINT", "neg1_smallint"),
        ("(-1)::INTEGER", "neg1_integer"),
        ("(-1)::BIGINT", "neg1_bigint"),
        ("(-128)::TINYINT", "neg128_tinyint"),
    ]
    for expr, key in neg_tests:
        emit("query I")
        emit(f"SELECT bitfilters_duckdb_hash('v1.5.1', {expr})::UBIGINT;")
        emit("----")
        emit(str(s[key]))
        emit()

    # NULL
    emit("# NULL propagates (standard DuckDB scalar function behavior)")
    emit("query T")
    emit("SELECT bitfilters_duckdb_hash('v1.5.1', NULL::INTEGER) IS NULL;")
    emit("----")
    emit("true")
    emit()

    # === Multi-value hash tests ===
    emit("# ============================================================================")
    emit("# bitfilters_duckdb_hash — multi-value (CombineHash)")
    emit("# ============================================================================")
    emit()

    multi_tests = [
        ("42, 'hello'", "42_hello"),
        ("1, 2, 3", "1_2_3"),
        ("42::INTEGER, 3.14::DOUBLE, 'test'::VARCHAR", "int_double_varchar"),
        ("42, 'test'", "42_test"),
    ]
    for expr, key in multi_tests:
        emit(f"# hash({expr})")
        emit("query I")
        emit(f"SELECT bitfilters_duckdb_hash('v1.5.1', {expr})::UBIGINT;")
        emit("----")
        emit(str(m[key]))
        emit()

    # === Cartesian product ===
    emit("# ============================================================================")
    emit("# bitfilters_duckdb_hash — cartesian product of type combinations")
    emit("# Types: VARCHAR('hi'), INTEGER(7), DOUBLE(2.5), BLOB('\\xDEAD')")
    emit("# ============================================================================")
    emit()

    type_exprs = {
        "hi": "'hi'",
        "7": "7",
        "2.5d": "2.5::DOUBLE",
        "dead": "'\\xDEAD'::BLOB",
    }
    for name_a, expr_a in type_exprs.items():
        for name_b, expr_b in type_exprs.items():
            key = f"{name_a}_x_{name_b}"
            emit(f"# hash({expr_a}, {expr_b})")
            emit("query I")
            emit(f"SELECT bitfilters_duckdb_hash('v1.5.1', {expr_a}, {expr_b})::UBIGINT;")
            emit("----")
            emit(str(c[key]))
            emit()

    # === Cross-version consistency ===
    emit("# ============================================================================")
    emit("# Cross-version consistency (v1.4.4 = v1.5.1 on little-endian)")
    emit(f"# Certified against DuckDB v1.4.4 (duckdb=={v144['duckdb_version']})")
    emit("# ============================================================================")
    emit()

    s144 = v144["single"]
    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.4.4', 42)::UBIGINT;")
    emit("----")
    emit(str(s144["42_integer"]))
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.4.4', 'hello')::UBIGINT;")
    emit("----")
    emit(str(s144["hello_varchar"]))
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.4.4', (-1)::TINYINT)::UBIGINT;")
    emit("----")
    emit(str(s144["neg1_tinyint"]))
    emit()

    m144 = v144["multi"]
    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.4.4', 42, 'hello')::UBIGINT;")
    emit("----")
    emit(str(m144["42_hello"]))
    emit()

    # v1.6.0 cross-version
    s160 = v160["single"]
    m160 = v160["multi"]

    emit(f"# Certified against DuckDB v1.6.0 (duckdb=={v160['duckdb_version']})")
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.6.0', 42)::UBIGINT;")
    emit("----")
    emit(str(s160["42_integer"]))
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.6.0', 'hello')::UBIGINT;")
    emit("----")
    emit(str(s160["hello_varchar"]))
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.6.0', (-1)::TINYINT)::UBIGINT;")
    emit("----")
    emit(str(s160["neg1_tinyint"]))
    emit()

    emit("query I")
    emit("SELECT bitfilters_duckdb_hash('v1.6.0', 42, 'hello')::UBIGINT;")
    emit("----")
    emit(str(m160["42_hello"]))
    emit()

    # Cross-version equality
    emit("query T")
    emit("SELECT bitfilters_duckdb_hash('v1.4.4', 42)::UBIGINT = bitfilters_duckdb_hash('v1.5.1', 42)::UBIGINT;")
    emit("----")
    emit("true")
    emit()

    emit("query T")
    emit("SELECT bitfilters_duckdb_hash('v1.5.1', 42)::UBIGINT = bitfilters_duckdb_hash('v1.6.0', 42)::UBIGINT;")
    emit("----")
    emit("true")
    emit()

    # Version without v prefix
    emit("query T")
    emit("SELECT bitfilters_duckdb_hash('1.5.1', 42)::UBIGINT = bitfilters_duckdb_hash('v1.5.1', 42)::UBIGINT;")
    emit("----")
    emit("true")
    emit()

    # === Error handling ===
    emit("# ============================================================================")
    emit("# Error handling")
    emit("# ============================================================================")
    emit()

    emit("statement error")
    emit("SELECT bitfilters_duckdb_hash('v0.0.0', 42);")
    emit("----")
    emit("Unsupported DuckDB version")
    emit()

    # === Bloom filter single key round-trip ===
    emit("# ============================================================================")
    emit("# Bloom filter — single key round-trip")
    emit("# ============================================================================")
    emit()

    emit("statement ok")
    emit("CREATE TABLE bf_keys AS SELECT i AS key FROM range(1000) t(i);")
    emit()
    emit("statement ok")
    emit("CREATE TABLE bf_filter AS")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 16384,")
    emit("    bitfilters_duckdb_hash('v1.5.1', key)) AS filter")
    emit("FROM bf_keys;")
    emit()
    emit("# All inserted keys found (no false negatives)")
    emit("query I")
    emit("SELECT COUNT(*) FROM bf_keys")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_filter), key);")
    emit("----")
    emit("1000")
    emit()
    emit("# Non-inserted keys: FPR < 2%")
    emit("query T")
    emit("SELECT COUNT(*) < 200 FROM range(10000, 20000) t(key)")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_filter), key);")
    emit("----")
    emit("true")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_keys;")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_filter;")
    emit()

    # === Bloom filter multi-key round-trip ===
    emit("# ============================================================================")
    emit("# Bloom filter — multi-key round-trip")
    emit("# ============================================================================")
    emit()

    emit("statement ok")
    emit("CREATE TABLE bf_multi AS SELECT i AS id, 'name_' || i AS name FROM range(500) t(i);")
    emit()
    emit("statement ok")
    emit("CREATE TABLE bf_multi_filter AS")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 8192,")
    emit("    bitfilters_duckdb_hash('v1.5.1', id, name)) AS filter")
    emit("FROM bf_multi;")
    emit()
    emit("query I")
    emit("SELECT COUNT(*) FROM bf_multi")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_multi_filter), id, name);")
    emit("----")
    emit("500")
    emit()
    emit("query T")
    emit("SELECT COUNT(*) < 100 FROM range(5000, 10000) t(i)")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_multi_filter), i, 'name_' || i);")
    emit("----")
    emit("true")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_multi;")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_multi_filter;")
    emit()

    # === Bloom filter error handling ===
    emit("# ============================================================================")
    emit("# Bloom filter error handling")
    emit("# ============================================================================")
    emit()

    emit("statement error")
    emit("SELECT bitfilters_duckdb_bloom_filter_probe('v0.0.0', '\\x00'::BLOB, 42);")
    emit("----")
    emit("Unsupported DuckDB version")
    emit()
    emit("statement error")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v0.0.0', 1024, 42::UBIGINT);")
    emit("----")
    emit("Unsupported DuckDB version")
    emit()
    emit("statement error")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 1000, 42::UBIGINT);")
    emit("----")
    emit("power of 2")
    emit()
    emit("statement error")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 0, 42::UBIGINT);")
    emit("----")
    emit("power of 2")
    emit()

    # === Edge cases ===
    emit("# ============================================================================")
    emit("# Edge cases")
    emit("# ============================================================================")
    emit()

    emit("# Empty aggregate returns NULL")
    emit("query T")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 1024,")
    emit("    bitfilters_duckdb_hash('v1.5.1', key)) IS NULL")
    emit("FROM (SELECT 1 AS key WHERE false);")
    emit("----")
    emit("true")
    emit()

    emit("# Bloom filter with negative integer keys")
    emit("statement ok")
    emit("CREATE TABLE bf_neg AS SELECT i AS key FROM range(-500, 0) t(i);")
    emit()
    emit("statement ok")
    emit("CREATE TABLE bf_neg_filter AS")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 8192,")
    emit("    bitfilters_duckdb_hash('v1.5.1', key)) AS filter")
    emit("FROM bf_neg;")
    emit()
    emit("query I")
    emit("SELECT COUNT(*) FROM bf_neg")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_neg_filter), key);")
    emit("----")
    emit("500")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_neg;")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_neg_filter;")
    emit()

    # === Large scale ===
    emit("# ============================================================================")
    emit("# Large scale test")
    emit("# ============================================================================")
    emit()

    emit("statement ok")
    emit("CREATE TABLE bf_large AS SELECT i AS key FROM range(10000) t(i);")
    emit()
    emit("statement ok")
    emit("CREATE TABLE bf_large_filter AS")
    emit("SELECT bitfilters_duckdb_bloom_filter_create('v1.5.1', 131072,")
    emit("    bitfilters_duckdb_hash('v1.5.1', key)) AS filter")
    emit("FROM bf_large;")
    emit()
    emit("query I")
    emit("SELECT COUNT(*) FROM bf_large")
    emit("WHERE bitfilters_duckdb_bloom_filter_probe('v1.5.1',")
    emit("    (SELECT filter FROM bf_large_filter), key);")
    emit("----")
    emit("10000")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_large;")
    emit()
    emit("statement ok")
    emit("DROP TABLE bf_large_filter;")


if __name__ == "__main__":
    main()
